version: '3.7'
services:
  dev_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres/data
    #  - ./postgres/init:/docker-entrypoint-initdb.d
    restart: always

volumes:
  db_data:
